name: Printing Dates
env:
  MY_NAME: 'manas tunga'
on:
  push:
    branches:
      - master

jobs:
  print-date-in-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: print MY_NAME
        run: |
        echo "accessing enviromental variable using shell syntax"

      - name: print date in ubuntu
        run: date


  # print-date-in-window:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Print date in windows
  #       run: Get-Date

  # print-date-in-mocos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Print date in macOS
  #       run: date

  # print-done:
  #   runs-on: ubuntu-latest
  #   needs: ["print-date-in-ubuntu","print-date-in-window","print-date-in-mocos"]
  #   steps:
  #     - name: Printing done
  #       run: echo done!!

  
     